project:
  type: website
  output-dir: _site
  resources:
    - CNAME
  render:
    - index.qmd
    - cv.qmd
    - research.qmd

website:
  title: "Mete Akcaoglu"
  navbar: false
  page-navigation: false

format:
  html:
    css: site-styles.css
    toc: false
    number-sections: false
    page-layout: article
    format-links: false
    include-before-body: _navbar.html
