project:
  type: website
  output-dir: _site
  resources:
    - CNAME
  render:
    - index.qmd
    - cv.qmd
    - research.qmd
    - projects.qmd
    - teaching.qmd
    - blog.qmd
    - posts

website:
  title: "Mete Akcaoglu"
  favicon: favicon.svg
  navbar: false
  page-navigation: false

format:
  html:
    css: site-styles.css
    toc: false
    number-sections: false
    page-layout: article
    format-links: false
    include-in-header: _includes/_analytics.html
    include-before-body: _includes/_navbar.html
    include-after-body: _includes/_footer.html
